openapi: 3.0.1
info:
  title: Derby DB API
  description: Spring Boot based rest api service for transport system to connect
    with Database
  version: v1
servers:
- url: http://localhost:8086
  description: Generated server url
tags:
- name: transport system database
  description: The Transport System database API
paths:
  /api/test:
    get:
      tags:
      - transport system database
      operationId: test
      responses:
        "200":
          description: default response
          content:
            application/json:
              schema:
                type: string
  /api/details:
    get:
      tags:
      - transport system database
      summary: Route Detail
      description: 'Find List of all routes along with distance and traffic delay  '
      operationId: getDetails
      responses:
        "200":
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RouteDetail'
  /api/planets:
    get:
      tags:
      - transport system database
      summary: Planet list
      description: 'Find List of all planets which is present in system '
      operationId: getPlanets
      responses:
        "200":
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Planet'
components:
  schemas:
    RouteDetail:
      type: object
      properties:
        routeId:
          type: integer
          format: int32
        planetOriginNode:
          type: string
        planetOriginName:
          type: string
        planetDestinationNode:
          type: string
        planetDestinationName:
          type: string
        distance:
          type: number
          format: double
        trafficDelay:
          type: number
          format: double
    Planet:
      type: object
      properties:
        id:
          type: integer
          format: int32
        planetNode:
          type: string
        planetName:
          type: string
